name: nectarjs
version: '0.1.7'
summary: God Mod for JavaScript
description: |
  Compile your JavaScript for everything
  
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:

  nectar:
    command: nectar
    plugs: [network-bind, home, network, removable-media, i2c]

  njs:
    command: njs
    plugs: [network-bind, home, network, removable-media, i2c]

parts:
  nectar:
    source: .
    plugin: nodejs
